### ISSUE TITLE
Update Mill 0.11 to 0.11.0-M8

### ISSUE THREAD

**Issue by lolgab** [lefou/mill-integrationtest#145]
I looked into it and the plugin and it uses the `import $exec` feature from Ammonite which was not ported to Mill. It needs to be updated to maybe support some mechanism based on `import $file` which is supported.

**Comment by lefou** [comment]
Yeah, I think `import $file` should work, but I ran into other issues. 

* https://github.com/lefou/mill-vcs-version/pull/102
* https://github.com/com-lihaoyi/mill/issues/2460

**Comment by lolgab** [comment]
That MatchError seems to be happening because mill doesn't know how to parse `import $exec.plugins` and doesn't fail with a nice error message. Changing it to  import $file should fix he problem.

**Comment by lefou** [comment]
> That MatchError seems to be happening because mill doesn't know how to parse `import $exec.plugins` and doesn't fail with a nice error message. Changing it to import $file should fix he problem.

Yeah, I know and already tested that. Yet, I ran into other issues. Need to analyze that later.

**Comment by lefou** [comment]
Closed by #147
