### ISSUE TITLE
Question: How to deal with `Unknown ansi-escape` when throwing exception in verify?

### ISSUE THREAD

**Issue by hmf** [lefou/mill-integrationtest#4]
First and foremost - nice work. Very useful library. It may even be a good way to generate and maintain a Mill *cookbook*. Second, I don't know if I should ask this in Mill's Gitter channel.  If so, please let me know so that I can ask there. 

The problem I have is that when implementing the `verify`command I throw an exception as I have observed being done in other modules. However this results in the following exception:

```
Exception in thread "main" java.lang.IllegalArgumentException: Unknown ansi-escape [2m at index 149 inside string cannot be parsed into an fansi.Str
	at fansi.ErrorMode$Throw$.handle(Fansi.scala:419)
	at fansi.ErrorMode$Throw$.handle(Fansi.scala:407)
	at fansi.Str$.apply(Fansi.scala:272)
	at fansi.Str$.implicitApply(Fansi.scala:227)
	at ammonite.MainRunner.printError(Main.scala:383)
	at ammonite.MainRunner.handleWatchRes(Main.scala:421)
	at mill.main.MainRunner.handleWatchRes(MainRunner.scala:118)
	at mill.main.MainRunner.watchLoop2(MainRunner.scala:58)
	at mill.main.MainRunner.runScript(MainRunner.scala:70)
	at mill.MillMain$.main0(MillMain.scala:187)
	at mill.MillMain$.main(MillMain.scala:27)
	at mill.MillMain.main(MillMain.scala)
```

I have thrown exceptions directly and indirectly in the following ways (`failures` is the number os `utest` failures):

```scala
  import $ivy.`com.lihaoyi::utest:0.7.1`
  import utest._

  import $ivy.`org.scalatest::scalatest:3.0.4`
  import org.scalatest.Assertions

  if (failures > 0) scala.Predef.assert(false)
  if (failures > 0) utest.assert(false)
  if (failures > 0) throw new java.lang.AssertionError("assertion failed")
  if (failures > 0) throw new java.lang.AssertionError(ufansi.Str("WT"))
  if (failures > 0) throw new java.lang.AssertionError("")
  val A = new Assertions{}
  import A._
  A.assert(false)
```
I have also tested with Java's `RuntimeException`and `Throwable`. Same result. It seems like all exception generate the `[2m`ANSI escape sequence. A look at the Ammonite code let me test the following 2 code lines:

```scala
  println(fansi.Str("Hello\u001b[2mWorld"))
  println(fansi.Str("Hello\u001b[2mWorld", fansi.ErrorMode.Throw)) // default
```
Both fail - generate this exception:

```
verify java.lang.IllegalArgumentException: Unknown ansi-escape [2m at index 5 inside string cannot be parsed into an fansi.Str
    fansi.ErrorMode$Throw$.handle(Fansi.scala:419)
    fansi.ErrorMode$Throw$.handle(Fansi.scala:407)
    fansi.Str$.apply(Fansi.scala:272)
    ammonite.$file.build.$anonfun$verify$2(build.sc:59)
    scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
```

But we can bypass this so:

```
  println("Sanitize")
  println(fansi.Str("Hello\u001b[2mWorld", fansi.ErrorMode.Sanitize))
  println("Strip")
  println(fansi.Str("Hello\u001b[2mWorld", fansi.ErrorMode.Strip))
```

Although it seem to be a [valid code](https://gist.github.com/dainkaplan/4651352) I would like to know if and how I can avoid this exception in Mill. 

TIA.

**Comment by lefou** [comment]
> First and foremost - nice work. Very useful library. It may even be a good way to generate and maintain a Mill _cookbook_. Second, I don't know if I should ask this in Mill's Gitter channel. If so, please let me know so that I can ask there.

Thank you. 

I think it's best to ask on Gitter (either mill or ammonite). I have no easy solution for this. (I'm sorry for my late response.)
