### ISSUE TITLE
Are plugins `moduleDeps` supported ?

### ISSUE THREAD

**Issue by lolgab** [lefou/mill-integrationtest#76]
I have a plugin that depends on a module via `moduleDeps`.
If I test it mill-integrationtest fails to resolve the module dependency.

**Comment by lefou** [comment]
I guess you found a bug. When running the test we publish all modules listed in `pluginsUnderTest` and `temporaryIvyModules`, but we forget to also traverse the `moduleDeps`. 

As a workaround, you may want to add the transitive modules to `temporaryIvyModules`.

**Comment by lefou** [comment]
@lolgab I implemented transitive publishing in PR #88.
